{
	"version": 1706540491,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/l3-sheet0.png",
		"images/l3-sheet1.png",
		"images/l2-sheet0.png",
		"images/l1-sheet0.png",
		"images/l4-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"media/rasazy voice.ogg",
		"media/victks voice.ogg",
		"media/rasazy voice2.ogg",
		"media/sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.ogg",
		"media/mixkit-laser-cannon-shot-1678.m4a",
		"media/mixkit-laser-cannon-shot-1678.ogg",
		"media/elektronomia & jjd - free [ncs release].ogg",
		"media/beta.ogg",
		"media/super-korova-muzyka-iz-geympleya-5.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}